import type { Question } from './types';

export const questions: Question[] = [
  {
    id: "q1",
    text: "What is the capital of France?",
    category: "geography",
    answer: "Paris",
    options: ["London", "Berlin", "Paris", "Madrid"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q2",
    text: "Who painted the Mona Lisa?",
    category: "art",
    answer: "Leonardo da Vinci",
    options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q3",
    text: "What year did World War II end?",
    category: "history",
    answer: "1945",
    options: ["1944", "1945", "1946", "1947"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q4",
    text: "What is the largest planet in our solar system?",
    category: "science",
    answer: "Jupiter",
    options: ["Saturn", "Jupiter", "Neptune", "Earth"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q5",
    text: "Which programming language was created by Brendan Eich?",
    category: "technology",
    answer: "JavaScript",
    options: ["Python", "Java", "JavaScript", "C++"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q6",
    text: "What is the chemical symbol for gold?",
    category: "science",
    answer: "Au",
    options: ["Go", "Gd", "Au", "Ag"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q7",
    text: "Who wrote 'To Kill a Mockingbird'?",
    category: "literature",
    answer: "Harper Lee",
    options: ["Mark Twain", "Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q8",
    text: "What is the smallest country in the world?",
    category: "geography",
    answer: "Vatican City",
    options: ["Monaco", "Liechtenstein", "Vatican City", "San Marino"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q9",
    text: "In which year did the Berlin Wall fall?",
    category: "history",
    answer: "1989",
    options: ["1987", "1988", "1989", "1990"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q10",
    text: "What is the fastest land animal?",
    category: "science",
    answer: "Cheetah",
    options: ["Lion", "Cheetah", "Leopard", "Tiger"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q11",
    text: "Which country is known as the 'Land of the Rising Sun'?",
    category: "geography",
    answer: "Japan",
    options: ["China", "Japan", "South Korea", "Thailand"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q12",
    text: "Who composed 'The Four Seasons'?",
    category: "art",
    answer: "Antonio Vivaldi",
    options: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonio Vivaldi", "Ludwig van Beethoven"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q13",
    text: "What is the largest ocean on Earth?",
    category: "geography",
    answer: "Pacific Ocean",
    options: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q14",
    text: "Which element has the atomic number 1?",
    category: "science",
    answer: "Hydrogen",
    options: ["Helium", "Hydrogen", "Lithium", "Carbon"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q15",
    text: "Who wrote '1984'?",
    category: "literature",
    answer: "George Orwell",
    options: ["Aldous Huxley", "Ray Bradbury", "George Orwell", "H.G. Wells"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q16",
    text: "What is the currency of Japan?",
    category: "geography",
    answer: "Yen",
    options: ["Won", "Yuan", "Yen", "Baht"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q17",
    text: "Which planet is known as the 'Red Planet'?",
    category: "science",
    answer: "Mars",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q18",
    text: "Who painted 'The Starry Night'?",
    category: "art",
    answer: "Vincent van Gogh",
    options: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q19",
    text: "What is the longest river in the world?",
    category: "geography",
    answer: "Nile",
    options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q20",
    text: "Which country hosted the 2016 Summer Olympics?",
    category: "geography",
    answer: "Brazil",
    options: ["Russia", "Brazil", "China", "United Kingdom"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q21",
    text: "What is the smallest unit of matter?",
    category: "science",
    answer: "Atom",
    options: ["Molecule", "Atom", "Cell", "Particle"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q22",
    text: "Who wrote 'Romeo and Juliet'?",
    category: "literature",
    answer: "William Shakespeare",
    options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q23",
    text: "What is the capital of Australia?",
    category: "geography",
    answer: "Canberra",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q24",
    text: "Which gas makes up most of Earth's atmosphere?",
    category: "science",
    answer: "Nitrogen",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q25",
    text: "Who composed 'Für Elise'?",
    category: "art",
    answer: "Ludwig van Beethoven",
    options: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Frédéric Chopin"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q26",
    text: "What is the largest desert in the world?",
    category: "geography",
    answer: "Antarctica",
    options: ["Sahara", "Gobi", "Antarctica", "Arabian"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q27",
    text: "Which programming language is known for its use in data science?",
    category: "technology",
    answer: "Python",
    options: ["Java", "C++", "Python", "JavaScript"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q28",
    text: "Who wrote 'The Great Gatsby'?",
    category: "literature",
    answer: "F. Scott Fitzgerald",
    options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q29",
    text: "What is the speed of light in a vacuum?",
    category: "science",
    answer: "299,792,458 m/s",
    options: ["299,792,458 m/s", "300,000,000 m/s", "299,000,000 m/s", "300,792,458 m/s"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q30",
    text: "Which country is the largest by land area?",
    category: "geography",
    answer: "Russia",
    options: ["Canada", "China", "Russia", "United States"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q31",
    text: "Who painted 'Guernica'?",
    category: "art",
    answer: "Pablo Picasso",
    options: ["Salvador Dalí", "Pablo Picasso", "Henri Matisse", "Joan Miró"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q32",
    text: "What is the hardest natural substance on Earth?",
    category: "science",
    answer: "Diamond",
    options: ["Gold", "Iron", "Diamond", "Quartz"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q33",
    text: "Which country has the most natural lakes?",
    category: "geography",
    answer: "Canada",
    options: ["Russia", "United States", "Canada", "Finland"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q34",
    text: "Who wrote 'Pride and Prejudice'?",
    category: "literature",
    answer: "Jane Austen",
    options: ["Charlotte Brontë", "Jane Austen", "Emily Brontë", "Virginia Woolf"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q35",
    text: "What is the largest mammal in the world?",
    category: "science",
    answer: "Blue whale",
    options: ["African elephant", "Blue whale", "Giraffe", "Hippopotamus"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q36",
    text: "Which country is home to the Great Wall?",
    category: "geography",
    answer: "China",
    options: ["Japan", "China", "India", "Mongolia"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q37",
    text: "Who composed 'The Nutcracker'?",
    category: "art",
    answer: "Pyotr Ilyich Tchaikovsky",
    options: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Pyotr Ilyich Tchaikovsky", "Ludwig van Beethoven"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q38",
    text: "What is the largest organ in the human body?",
    category: "science",
    answer: "Skin",
    options: ["Liver", "Lungs", "Skin", "Brain"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q39",
    text: "Which country has the most active volcanoes?",
    category: "geography",
    answer: "Indonesia",
    options: ["Japan", "Indonesia", "Iceland", "Philippines"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q40",
    text: "Who wrote 'The Catcher in the Rye'?",
    category: "literature",
    answer: "J.D. Salinger",
    options: ["Ernest Hemingway", "J.D. Salinger", "F. Scott Fitzgerald", "John Steinbeck"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q41",
    text: "What is the most abundant gas in Earth's atmosphere?",
    category: "science",
    answer: "Nitrogen",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q42",
    text: "Which country is known as the 'Pearl of the Orient'?",
    category: "geography",
    answer: "Philippines",
    options: ["Thailand", "Philippines", "Malaysia", "Singapore"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q43",
    text: "Who painted 'The Persistence of Memory'?",
    category: "art",
    answer: "Salvador Dalí",
    options: ["Pablo Picasso", "Salvador Dalí", "René Magritte", "Joan Miró"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q44",
    text: "What is the smallest bone in the human body?",
    category: "science",
    answer: "Stapes",
    options: ["Femur", "Stapes", "Tibia", "Radius"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q45",
    text: "Which country has the longest coastline?",
    category: "geography",
    answer: "Canada",
    options: ["Russia", "Australia", "Canada", "United States"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q46",
    text: "Who wrote 'The Lord of the Rings'?",
    category: "literature",
    answer: "J.R.R. Tolkien",
    options: ["C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin", "Terry Pratchett"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q47",
    text: "What is the largest planet in our solar system?",
    category: "science",
    answer: "Jupiter",
    options: ["Saturn", "Jupiter", "Neptune", "Earth"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q48",
    text: "Which country is home to Machu Picchu?",
    category: "geography",
    answer: "Peru",
    options: ["Mexico", "Peru", "Chile", "Bolivia"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q49",
    text: "Who composed 'Swan Lake'?",
    category: "art",
    answer: "Pyotr Ilyich Tchaikovsky",
    options: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Pyotr Ilyich Tchaikovsky", "Ludwig van Beethoven"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q50",
    text: "What is the largest living structure on Earth?",
    category: "science",
    answer: "Great Barrier Reef",
    options: ["Great Wall of China", "Great Barrier Reef", "Amazon Rainforest", "Himalayas"],
    revealedQuestion: false,
    openOptions: false,
  }
];
