import type { Question } from './types';

export const questions: Question[] = [
  {
    id: "q1",
    text: "What is the capital of France?",
    category: "geography",
    answer: "Paris",
    options: ["London", "Berlin", "Paris", "Madrid"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q2",
    text: "Who painted the Mona Lisa?",
    category: "art",
    answer: "Leonardo da Vinci",
    options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q3",
    text: "What year did World War II end?",
    category: "history",
    answer: "1945",
    options: ["1944", "1945", "1946", "1947"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q4",
    text: "What is the largest planet in our solar system?",
    category: "science",
    answer: "Jupiter",
    options: ["Saturn", "Jupiter", "Neptune", "Earth"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q5",
    text: "Which programming language was created by Brendan Eich?",
    category: "technology",
    answer: "JavaScript",
    options: ["Python", "Java", "JavaScript", "C++"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q6",
    text: "What is the chemical symbol for gold?",
    category: "science",
    answer: "Au",
    options: ["Go", "Gd", "Au", "Ag"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q7",
    text: "Who wrote 'To Kill a Mockingbird'?",
    category: "literature",
    answer: "Harper Lee",
    options: ["Mark Twain", "Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q8",
    text: "What is the smallest country in the world?",
    category: "geography",
    answer: "Vatican City",
    options: ["Monaco", "Liechtenstein", "Vatican City", "San Marino"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q9",
    text: "In which year did the Berlin Wall fall?",
    category: "history",
    answer: "1989",
    options: ["1987", "1988", "1989", "1990"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q10",
    text: "What is the fastest land animal?",
    category: "science",
    answer: "Cheetah",
    options: ["Lion", "Cheetah", "Leopard", "Tiger"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q11",
    text: "Which company developed the iPhone?",
    category: "technology",
    answer: "Apple",
    options: ["Samsung", "Google", "Apple", "Microsoft"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q12",
    text: "What is the currency of Japan?",
    category: "geography",
    answer: "Yen",
    options: ["Won", "Yuan", "Yen", "Baht"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q13",
    text: "Who composed 'The Four Seasons'?",
    category: "music",
    answer: "Antonio Vivaldi",
    options: ["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonio Vivaldi", "Ludwig van Beethoven"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q14",
    text: "What is the longest river in the world?",
    category: "geography",
    answer: "Nile",
    options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q15",
    text: "Which element has the atomic number 1?",
    category: "science",
    answer: "Hydrogen",
    options: ["Helium", "Hydrogen", "Lithium", "Carbon"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q16",
    text: "Who directed the movie 'Pulp Fiction'?",
    category: "entertainment",
    answer: "Quentin Tarantino",
    options: ["Martin Scorsese", "Quentin Tarantino", "Steven Spielberg", "Christopher Nolan"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q17",
    text: "What is the largest ocean on Earth?",
    category: "geography",
    answer: "Pacific",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q18",
    text: "Which country hosted the 2016 Summer Olympics?",
    category: "sports",
    answer: "Brazil",
    options: ["Japan", "Brazil", "United Kingdom", "China"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q19",
    text: "What is the hardest natural substance on Earth?",
    category: "science",
    answer: "Diamond",
    options: ["Gold", "Iron", "Diamond", "Quartz"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q20",
    text: "Who was the first person to walk on the moon?",
    category: "history",
    answer: "Neil Armstrong",
    options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q21",
    text: "What is the capital of Australia?",
    category: "geography",
    answer: "Canberra",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q22",
    text: "Which planet is known as the 'Red Planet'?",
    category: "science",
    answer: "Mars",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q23",
    text: "What is the largest mammal in the world?",
    category: "science",
    answer: "Blue whale",
    options: ["African elephant", "Blue whale", "Giraffe", "Hippopotamus"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q24",
    text: "Who wrote '1984'?",
    category: "literature",
    answer: "George Orwell",
    options: ["Aldous Huxley", "Ray Bradbury", "George Orwell", "H.G. Wells"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q25",
    text: "What is the smallest prime number?",
    category: "mathematics",
    answer: "2",
    options: ["1", "2", "3", "5"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q26",
    text: "Which country is known as the 'Land of the Rising Sun'?",
    category: "geography",
    answer: "Japan",
    options: ["China", "Japan", "South Korea", "Thailand"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q27",
    text: "What is the speed of light in a vacuum?",
    category: "science",
    answer: "299,792,458 m/s",
    options: ["299,792,458 m/s", "300,000,000 m/s", "299,000,000 m/s", "300,792,458 m/s"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q28",
    text: "Who painted 'The Starry Night'?",
    category: "art",
    answer: "Vincent van Gogh",
    options: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q29",
    text: "What is the largest continent by area?",
    category: "geography",
    answer: "Asia",
    options: ["Africa", "Asia", "North America", "Europe"],
    revealedQuestion: false,
    openOptions: false,
  },
  {
    id: "q30",
    text: "Which programming paradigm does JavaScript primarily follow?",
    category: "technology",
    answer: "Multi-paradigm",
    options: ["Object-oriented only", "Functional only", "Multi-paradigm", "Procedural only"],
    revealedQuestion: false,
    openOptions: false,
  },
];
